# Generated by Django 4.1.7 on 2023-03-20 04:16

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('org_name', models.CharField(blank=True, max_length=200, null=True)),
                ('title', models.CharField(max_length=15, verbose_name='Name')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='portfolio')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Experience',
                'verbose_name_plural': 'Work Experiences',
                'ordering': ['org_name'],
            },
        ),
        migrations.DeleteModel(
            name='Portfolio',
        ),
    ]
