# Generated by Django 3.2.10 on 2023-03-20 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20230320_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='is_key_skill',
        ),
    ]
