# Generated by Django 3.2.10 on 2023-04-06 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_skill_is_key_skill'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactProfile',
        ),
    ]
